### ISSUE TITLE
Support burning secrets with passphrase

### ISSUE THREAD

**Issue by xakraz** [emdneto/otsgo#10]
I am trying to burn a secret with the CLI but I get a 404 unknown secret (despite the fact that I get the METADATA_KEY from `ots get recent`.

```
$ ots burn METADATA_KEY

https://onetimesecret.com/api/v1/private/METADATA_KEY/burn
404 Unknown secret
```

While going on the WebUI of OneTimeSecret, I saw: "provide the passphrase of the secret"

According to the API Doc:

```
Burn a secret
POST https://onetimesecret.com/api/v1/private/METADATA_KEY/burn
Burn a secret that has not been read yet.

Query Params
* None

Attributes
* Same as metadata attributes with a status of burned.

Example:
$ curl -X POST -u 'USERNAME:APITOKEN' https://onetimesecret.com/api/v1/private/METADATA_KEY/burn
```

Thanks!

**Comment by emdneto** [comment]
Hi: You should use a valid metdatakey (the private key).
